name:                LambdaDesigner-Experiments
version:             0.1.0.0
github:              "ulyssesp/LambdaDesigner-Experiments"
license:             BSD3
author:              "Ulysses Popple"
maintainer:          "ulysses.popple@gmail.com"
copyright:           "2017 Ulysses Popple"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/LambdaDesigner-Experiments#readme>

dependencies:
- base >= 4.7 && < 5
- LambdaDesigner
- bytestring
- lens
- matrix

library:
  source-dirs: src

executables:
  LambdaDesigner-Experiments-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambdaDesigner-Experiments

tests:
  LambdaDesigner-Experiments-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambdaDesigner-Experiments
